### ISSUE TITLE
Bitfield draw error

### ISSUE THREAD

**Issue by yarkomar18** [wifasoi/WaveDromTikZ#5]
Bitfield can’t be drawn, the script gives an error :(
-
```
[
    { "name": "IPO",   "bits": 8, "attr": "RO" },
    {                  "bits": 7 },
    { "name": "BRK",   "bits": 5, "attr": "RW", "type": 4 },
    { "name": "CPK",   "bits": 1 },
    { "name": "Clear", "bits": 3 },
    { "bits": 8 }
]
```

./wavedromtikz.py wavedrom bitfield.drom
```
Traceback (most recent call last):
  File "./wavedromtikz.py", line 875, in <module>
    args.func(args)
  File "./wavedromtikz.py", line 836, in print_render_wavedrom
    wavedrom = render_wavedrom(yaml.safe_load(input_file.read()))
  File "./wavedromtikz.py", line 817, in render_wavedrom
    hscale = wavedrom.get("config", {}).get("hscale",1)
AttributeError: 'list' object has no attribute 'get'
```

But simple timing diagrams with no problem, thank you very much for that!

**Comment by wifasoi** [comment]
Your wavedrom definition is not correct (quickly checked via: https://wavedrom.com/editor.html).
it should be:
```
{ reg:[
    { "name": "IPO",   "bits": 8, "attr": "RO" },
    {                  "bits": 7 },
    { "name": "BRK",   "bits": 5, "attr": "RW", "type": 4 },
    { "name": "CPK",   "bits": 1 },
    { "name": "Clear", "bits": 3 },
    { "bits": 8 }
]}
```
So I'm expect a dictionary, and you gave me a list.. so the code will trow a fit at you when try to fetch the config :D
As this is just a simple script, I don't do a formatting check on the wavedrom input (I should but I don't have much time now).
Anywhay I'll leave this issue open as a todo.

**Comment by NLS-04** [comment]
@wifasoi is the script even capable of handling registers?
I have the same problems converting bitfield wavedroms.

Trying the corrected version above with python3.14 or python3.10 will return the following error:

```sh
$ python wavedromtikz.py wavedrom test.drom
wavedromtikz.py:788: SyntaxWarning: "\_" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\_"? A raw string is also an option.
  signal_params.get("name", "").replace('_', '\_'),
Traceback (most recent call last):
  File "C:\Users\nicsc\Desktop\RISC-V Summit\wavedromtikz.py", line 875, in <module>
    args.func(args)
    ~~~~~~~~~^^^^^^
  File "C:\Users\nicsc\Desktop\RISC-V Summit\wavedromtikz.py", line 836, in print_render_wavedrom
    wavedrom = render_wavedrom(yaml.safe_load(input_file.read()))
  File "C:\Users\nicsc\Desktop\RISC-V Summit\wavedromtikz.py", line 819, in render_wavedrom
    render_help_lines(wavedrom),
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\nicsc\Desktop\RISC-V Summit\wavedromtikz.py", line 800, in render_help_lines
    for signal in wavedrom["signal"]
                  ~~~~~~~~^^^^^^^^^^
KeyError: 'signal'
```

**Comment by wifasoi** [comment]
Yes, but remember that it need to be a valid wavedrom file (and i do not do input validation). So registers need to be defined like:
```
{ 
  reg:[
     ...
  ]
}
```
You can try to copy and paste your wavedrom file in the wavedrom editor https://wavedrom.com/editor.html and check yourself if there is something wrong with your register definition.

If it renders, I'm gonna ask you if you can paste here your wavedrom diagram, so i can reproduce the error.

**Comment by NLS-04** [comment]
The error output form python i got above was returned by using the wavedrom you replied with 2024:

> Your wavedrom definition is not correct (quickly checked via: https://wavedrom.com/editor.html). it should be:
> 
> ```
> { reg:[
>     { "name": "IPO",   "bits": 8, "attr": "RO" },
>     {                  "bits": 7 },
>     { "name": "BRK",   "bits": 5, "attr": "RW", "type": 4 },
>     { "name": "CPK",   "bits": 1 },
>     { "name": "Clear", "bits": 3 },
>     { "bits": 8 }
> ]}
> ```
> 
> So I'm expect a dictionary, and you gave me a list.. so the code will trow a fit at you when try to fetch the config :D As this is just a simple script, I don't do a formatting check on the wavedrom input (I should but I don't have much time now). Anywhay I'll leave this issue open as a todo.
